#!/usr/bin/env python3
"""
Tag normalization script for wiki.

Usage:
  python3 scripts/tag_normalization.py [--dry-run]

Scans all entities/, concepts/, comparisons/ pages.
Normalizes tags using a comprehensive synonym map.
Updates SCHEMA.md if new canonical tags are needed.
"""
import re, os, sys

wiki = os.path.expanduser("~/wiki")

# Tag synonym map: non_standard_tag → canonical_tag
TAG_NORMALIZATION = {
    # Case issues
    'RAG': 'rag', 'AI-agents': 'ai-agents', 'NLP': 'nlp',
    'OpenAI': 'openai', 'SaaS': 'saas', 'OAuth': 'oauth', 'RLM': 'rlm',

    # Common synonyms → canonical
    'llm': 'model', 'llms': 'model', 'models': 'model',
    'system-architecture': 'architecture',
    'research': 'lab',
    'developer-tools': 'developer-tooling', 'devtools': 'developer-tooling',
    'ai-safety': 'agent-safety',
    'retrieval': 'rag', 'retrieval-augmented-generation': 'rag',
    'agent-infrastructure': 'ai-agents', 'agent': 'ai-agents',
    'gpt': 'model',
    'enterprise': 'company',
    'prompt-engineering': 'prompting',
    'memory': 'memory-systems',
    'evals': 'evaluation', 'evaluations': 'evaluation', 'llm-evaluation': 'evaluation',
    'claude': 'anthropic',
    'serving': 'inference', 'llm-serving': 'inference',
    'distributed-training': 'training',
    'gpu': 'inference', 'cuda': 'inference',
    'agent-memory': 'ai-agents', 'ai-agent': 'ai-agents',
    'ai-evals': 'evaluation', 'ai-eval': 'evaluation',
    'ai-coding': 'coding-agents', 'coding': 'coding-agents',
    'inference-optimization': 'optimization',
    'saas': 'product',
    'speech': 'multimodal',
    'cybersecurity': 'security',
    'agent-team-swarm': 'multi-agent', 'agent-swarm': 'multi-agent',
    'post-training': 'training', 'pre-training': 'training',
    'startup': 'company', 'startups': 'company',
    'embeddings': 'model', 'tokenizer': 'model',
    'lora': 'fine-tuning', 'qlora': 'fine-tuning', 'peft': 'fine-tuning',
    'gguf': 'quantization',
    'sandboxing': 'sandbox',
    'code-execution': 'coding-agents',
    'agent-engineering': 'agentic-engineering',
    'agentic-ai': 'ai-agents',
    'agent-framework': 'ai-agents', 'agent-frameworks': 'ai-agents',
    'multi-agent-orchestration': 'orchestration',
    'llm-training': 'training', 'rl-training': 'training',
    'finetuning': 'fine-tuning', 'ft': 'fine-tuning',
    'rlhf': 'fine-tuning',
    'context-window': 'context-management',
    'prompt-injection': 'agent-safety',
    'open-models': 'open-source', 'open-weights': 'open-source',
    'open-source-ai': 'open-source',
    'semantic-search': 'search', 'vector-search': 'search',
    'agentic-search': 'search',
    'knowledge-graph': 'rag', 'graphrag': 'rag',
    'hugging-face': 'huggingface',
    'frontier-model': 'model', 'frontier-models': 'model',
    'deep-learning': 'model', 'machine-learning': 'model',
    'generative-ai': 'model', 'generative-models': 'model',
    'large-language-models': 'model',
    'enterprise-ai': 'company',
    'ai-startup': 'startup',
    'solo-founder': 'person', 'founder': 'person',
    'venture-capital': 'company',
    'ai-researcher': 'person', 'researcher': 'person',
    'research-paper': 'benchmark',
    'rl': 'training', 'reinforcement': 'training',
    'dpo': 'training', 'orpo': 'training', 'kto': 'training', 'grpo': 'training',
    'ai-engineering': 'agentic-engineering',
    'agent-orchestration': 'orchestration',
    'multi-agent-orchestration': 'orchestration',
    'ai-lab': 'lab',
    'ai-research': 'lab',
    'agentic-workflows': 'workflow', 'agent-workflow': 'workflow',
    'prompts': 'prompting', 'prompt-optimization': 'optimization',
    'red-teaming': 'agent-safety',
    'code-review': 'coding-agents',
    'tool-use': 'tool', 'tool-calling': 'tool',
    'agent-tools': 'tool',
    'agent-evals': 'evaluation', 'agent-evaluation': 'evaluation',
    'agent-capabilities': 'ai-agents',
    'computer-use': 'ai-agents',
    'inference-scaling': 'inference', 'inference-time-scaling': 'inference',
    'gpu-inference': 'inference',
    'llm-optimization': 'optimization', 'model-optimization': 'optimization',
    'cost-optimization': 'optimization',
    'llm-engineering': 'model',
    'leaderboard': 'benchmark', 'benchmarks': 'benchmark',
    'llm-as-judge': 'evaluation',
    'model-evaluation': 'evaluation',
    'distributed-systems': 'architecture',
    'agent-design': 'agentic-engineering', 'agent-patterns': 'agentic-engineering',
    'agent-architecture': 'architecture',
    'hackernews': 'hn-popular',
    'entrepreneur': 'person',
    'entrepreneurship': 'company',
    'labs': 'lab',
    'investor': 'company',
    'yc': 'company',
    'finetuning': 'fine-tuning',
    'hyperparameter': 'fine-tuning',
    'feature-store': 'infrastructure',
    'feature-engineering': 'infrastructure',
    'ml-pipeline': 'infrastructure',
    'etl': 'infrastructure',
    'data-pipeline': 'infrastructure',
    'artifact-store': 'infrastructure',
    'model-registry': 'infrastructure',
    'experiment-tracking': 'infrastructure',
    'data-versioning': 'infrastructure',
    'adversarial': 'agent-safety',
    'zero-trust': 'security',
    'excessive-agency': 'agent-safety',
    'red-team': 'agent-safety',
    'dual-use': 'agent-safety',
    'leak': 'agent-safety',
    'instruct': 'prompting',
    'system-prompt': 'prompting',
    'few-shot': 'prompting',
    'cot': 'reasoning',
    'chain-of-thought': 'reasoning',
    'tree-of-thought': 'reasoning',
    'thinking': 'reasoning',

    # 2026-05-08 expansion: tags with >=5 wiki uses not in SCHEMA
    'agent-security': 'agent-safety',
    'agent-harness': 'harness-engineering',
    'ai-agent': 'ai-agents', 'agents': 'ai-agents',
    'author': 'person', 'ml-researcher': 'person',
    'organization': 'company',
    'benchmarking': 'benchmark', 'benchmarks': 'benchmark',
    'llm-evaluation': 'evaluation', 'agent-evaluation': 'evaluation',
    'ai-infrastructure': 'infrastructure', 'ai-infra': 'infrastructure',
    'ml-infrastructure': 'infrastructure', 'ml-engineering': 'infrastructure',
    'data-engineering': 'infrastructure', 'ml-pipeline': 'infrastructure',
    'devops': 'developer-tooling', 'cli': 'developer-tooling',
    'ide': 'developer-tooling', 'api': 'developer-tooling',
    'rust': 'developer-tooling', 'python': 'developer-tooling',
    'typescript': 'developer-tooling', 'javascript': 'developer-tooling',
    'zig': 'developer-tooling', 'elixir': 'developer-tooling',
    'bun': 'developer-tooling', 'deno': 'developer-tooling',
    'nodejs': 'developer-tooling', 'lisp': 'developer-tooling',
    'filesystem': 'developer-tooling', 'git': 'developer-tooling',
    'docker': 'developer-tooling', 'pydantic': 'developer-tooling',
    'cloud': 'infrastructure', 'observability': 'infrastructure',
    'monitoring': 'infrastructure', 'reliability': 'infrastructure',
    'browser-automation': 'browser-agent',
    'managed-agents': 'ai-agents', 'subagents': 'ai-agents',
    'autonomous-agents': 'ai-agents', 'computer-use': 'ai-agents',
    'tts': 'multimodal', 'audio': 'multimodal', 'voice': 'multimodal',
    'audio-codec': 'multimodal', 'speech': 'multimodal',
    'long-context': 'context-management', 'cognitive-load': 'context-management',
    'scaling': 'optimization', 'efficiency': 'optimization',
    'synthetic-data': 'training', 'distillation': 'training',
    'fsdp': 'training', 'deepspeed': 'training', 'accelerate': 'training',
    'post-training': 'training', 'distributed-training': 'training',
    'gpu': 'hardware', 'vram': 'hardware', 'apple-silicon': 'hardware',
    'ollama': 'local-llm', 'ggml': 'quantization', 'gptq': 'quantization',
    'qlora': 'fine-tuning', 'unsloth': 'fine-tuning', 'trl': 'fine-tuning',
    'instructor': 'developer-tooling', 'langsmith': 'langchain',
    'chatgpt': 'openai', 'codex': 'coding-agents',
    'devin': 'coding-agents', 'cursor': 'coding-agents',
    'claude': 'anthropic', 'gemini': 'google', 'deepmind': 'google',
    'google-deepmind': 'google', 'amazon': 'aws',
    'coreweave': 'infrastructure', 'ai-coding': 'coding-agents',
    'rlhf': 'fine-tuning', 'information-retrieval': 'search',
    'simon-willison': 'person', 'karpathy': 'person', 'gwern': 'person',
    'solo-founder': 'person', 'founder': 'person', 'researcher': 'person',
    'entrepreneur': 'person', 'engineer': 'person', 'programmer': 'person',
    'designer': 'person', 'writer': 'person', 'educator': 'person',
    'technology': 'developer-tooling', 'technique': 'methodology',
    'ai': 'model', 'meta': 'methodology',
    'autonomous-vehicles': 'robotics', 'free-software': 'open-source',
    'llm-tools': 'tool', 'design-patterns': 'methodology',
    'productivity': 'developer-tooling', 'quotes': 'methodology',
    'competitive-analysis': 'methodology', 'ml-research': 'lab',
    'information-theory': 'methodology', 'harness': 'harness-engineering',
    'bitter-lesson': 'methodology', 'web-security': 'security',
    'dom-based': 'developer-tooling', 'financial-services': 'fintech',
    'llm-education': 'education', 'systems-programming': 'developer-tooling',
    'index': 'methodology',  # metadata tags

    # 2026-05-11 expansion: additional non-SCHEMA tags found in weekly audit
    'knowledge': 'methodology',
    'ai-benchmarks': 'benchmark',
    'ai-economics': 'economics',
    'data-analysis': 'data-science',
    'deployment': 'devops',
    'microservices': 'architecture',
    'emergence': 'ai',
    'turing-completeness': 'model',
    'parallelism': 'optimization',
    'model-comparison': 'comparison',
    'vision': 'multimodal',
    'course': 'education',
    'documentation': 'developer-tooling',
    'speaking': 'writing',
    'python-developer': 'developer-tooling',
    'lm-eval': 'evaluation',
    'podcast': 'writing',
    'e-commerce': 'fintech',
    'developer': 'developer-tooling',
    'vertical-ai': 'ai-adoption',
    'context-graphs': 'information-retrieval',
    'lambda': 'serverless',
    'claude-mythos': 'anthropic',
    'sierra': 'company',
    'searchcode': 'search',
    'every-inc': 'company',

    'monte-carlo-tree-search': 'reasoning',
    'planning': 'reasoning',
    'tool-planning': 'reasoning',
    'self-consistency': 'reasoning',
    'reflexion': 'reasoning',
    'critique': 'reasoning',
    'self-critique': 'reasoning',
    'self-reflection': 'reasoning',
    'synthetic-data': 'training',
    'data-augmentation': 'training',
    'distillation': 'training',
    'model-distillation': 'training',
    'pruning': 'quantization',
    'sparsity': 'quantization',
    'moe': 'model',
    'mixture-of-experts': 'model',
    'transformer': 'model',
    'attention': 'model',
    'multi-head-attention': 'model',
    'linear-attention': 'model',
    'flash-attention': 'inference',
    'paged-attention': 'inference',
    'continuous-batching': 'inference',
    'dynamic-batching': 'inference',
    'speculative-decoding': 'inference',
    'guided-generation': 'inference',
    'json-mode': 'inference',
    'grammar-constrained-decoding': 'inference',
    'structuredgeneration': 'inference',
    'outlines': 'inference',
    'guidance': 'inference',
    'lmql': 'inference',
    'docstring': 'developer-tooling',
    'type-hints': 'developer-tooling',
    'pydantic': 'developer-tooling',
    'fastapi': 'developer-tooling',
    'pytest': 'developer-tooling',
    'unittest': 'developer-tooling',
    'mocking': 'developer-tooling',
    'ci': 'developer-tooling',
    'cd': 'developer-tooling',
    'docker': 'developer-tooling',
    'container': 'developer-tooling',
    'kubernetes': 'developer-tooling',
    'terraform': 'developer-tooling',
    'ansible': 'developer-tooling',
    'helm': 'developer-tooling',
    'gitops': 'developer-tooling',
    'monorepo': 'developer-tooling',
    'observability': 'infrastructure',
    'monitoring': 'infrastructure',
    'logging': 'infrastructure',
    'tracing': 'infrastructure',
    'opentelemetry': 'infrastructure',
    'prometheus': 'infrastructure',
    'grafana': 'infrastructure',
    'datadog': 'infrastructure',
    'newrelic': 'infrastructure',
    'sentry': 'infrastructure',
    'error-budget': 'infrastructure',
    'sla': 'infrastructure',
    'slo': 'infrastructure',
    'reliability-engineering': 'infrastructure',
    'chaos-engineering': 'infrastructure',
    'resilience': 'infrastructure',
    'fault-tolerance': 'infrastructure',
    'disaster-recovery': 'infrastructure',
    'high-availability': 'infrastructure',
    'load-balancing': 'infrastructure',
    'autoscaling': 'infrastructure',
    'rate-limiting': 'infrastructure',
    'circuit-breaker': 'infrastructure',
    'retry-logic': 'infrastructure',
    'backpressure': 'infrastructure',
    'message-queue': 'infrastructure',
    'event-streaming': 'infrastructure',
    'stream-processing': 'infrastructure',
    'batch-processing': 'infrastructure',
    'real-time': 'infrastructure',
    'serverless': 'infrastructure',
    'function-as-a-service': 'infrastructure',
    'edge-computing': 'infrastructure',
    'cdn': 'infrastructure',
    'dns': 'infrastructure',
    'api-gateway': 'infrastructure',
    'reverse-proxy': 'infrastructure',
    'service-mesh': 'infrastructure',
    'sidecar': 'infrastructure',
    'envoy': 'infrastructure',
    'istio': 'infrastructure',
    'grpc': 'protocol',
    'rest': 'protocol',
    'graphql': 'protocol',
    'websocket': 'protocol',
    'http2': 'protocol',
    'http3': 'protocol',
    'protobuf': 'protocol',
    'avro': 'protocol',
    'parquet': 'protocol',
    'arrow': 'protocol',
    'ipc': 'protocol',
    'posix': 'protocol',
    'virtio': 'protocol',
    'nvlink': 'protocol',
    'pcie': 'protocol',
    'cxl': 'protocol',
    'ccix': 'protocol',
    'ib': 'protocol',
    'rdma': 'protocol',
    'roce': 'protocol',
    'nvmeof': 'protocol',
    'nvme': 'protocol',
    'scsi': 'protocol',
    'raid': 'protocol',
    'hdfs': 'protocol',
    's3': 'protocol',
    's3-compatible': 'protocol',
    'gcs': 'protocol',
    'azure-blob': 'protocol',
    'block-storage': 'protocol',
    'object-storage': 'protocol',
    'file-storage': 'protocol',
    'nas': 'protocol',
    'san': 'protocol',
    'lun': 'protocol',
    'fabric': 'protocol',
    'fibre-channel': 'protocol',
    'ethernet': 'protocol',
    'infiniband': 'protocol',
    'nvswitch': 'protocol',
    'nvlink-fabric': 'protocol',
    'dgx': 'hardware',
    'hgx': 'hardware',
    'h100': 'hardware',
    'h200': 'hardware',
    'b100': 'hardware',
    'b200': 'hardware',
    'b300': 'hardware',
    'a100': 'hardware',
    'a6000': 'hardware',
    'a6000-48gb': 'hardware',
    'rtx': 'hardware',
    'tpu': 'hardware',
    'inferentia': 'hardware',
    'trainium': 'hardware',
    'habana': 'hardware',
    'gaudi': 'hardware',
    'cerebras': 'hardware',
    'groq': 'hardware',
    'samba-nova': 'hardware',
    'graphcore': 'hardware',
    'tenstorrent': 'hardware',
    'systolic-array': 'hardware',
    'hbm': 'hardware',
    'gddr': 'hardware',
    'nvlink': 'hardware',
    'pcie': 'hardware',
    'nvme': 'hardware',
    'ssd': 'hardware',
    'nvram': 'hardware',
    'optane': 'hardware',
    'cxl': 'hardware',
    'ccix': 'hardware',
    'ib': 'hardware',
    'rdma': 'hardware',
    'roce': 'hardware',
    'nvmeof': 'hardware',
    'nvme-tcp': 'hardware',
    'nvme-rdma': 'hardware',
    'nvme-fc': 'hardware',
    'nvme-ib': 'hardware',
    'nvme-over-fabrics': 'hardware',
    'nvme-ssd': 'hardware',
    'nvme-of': 'hardware',
    'nvme-rdma': 'hardware',
    'nvme-tcp': 'hardware',
    'nvme-fc': 'hardware',
    'nvme-ib': 'hardware',
    'nvme-over-fabrics': 'hardware',
    'nvme-ssd': 'hardware',
    'nvme-of': 'hardware',
    'nvme-rdma': 'hardware',
    'nvme-tcp': 'hardware',
    'nvme-fc': 'hardware',
    'nvme-ib': 'hardware',
    'nvme-over-fabrics': 'hardware',
    'nvme-ssd': 'hardware',
    'nvme-of': 'hardware',
    'nvme-rdma': 'hardware',
    'nvme-tcp': 'hardware',
    'nvme-fc': 'hardware',
    'nvme-ib': 'hardware',
    'nvme-over-fabrics': 'hardware',

    # 2026-05-11 phase2: remaining high-frequency non-SCHEMA tags (≥3x)
    'technology': 'developer-tooling',
    'sysadmin': 'developer-tooling',
    'unix': 'developer-tooling',
    'hermes-agent': 'ai-agents',
    'vision-language': 'multimodal',
    'cryptography': 'security',
    'neural-audio': 'multimodal',
    'MCP': 'protocol',
    'prime-intellect': 'company',
    'newsletter': 'writing',
    'dgx-spark': 'hardware',
    'linux': 'developer-tooling',
    'physical-ai': 'robotics',
    'grok': 'model',
    'aec': 'industry',
    'projects': 'methodology',
    'free-software': 'open-source',
    'acp': 'protocol',
    'generative-ui': 'developer-tooling',
    'programming': 'developer-tooling',
    'acquisition': 'company',
    'tech-criticism': 'writing',
    'tech-commentary': 'writing',
    'spacex': 'company',
    'gemma': 'model',
    'performance': 'optimization',
    'token-efficiency': 'optimization',
    'identity': 'methodology',
    'agentic-rag': 'rag',
    'tool-design': 'tool',
    'monty': 'company',
    'self-hosting': 'infrastructure',
    'debugging': 'developer-tooling',
    'workflow-design': 'workflow',
    'model-compression': 'quantization',
    'a2a': 'protocol',
    'cloudflare': 'company',
    'skill-management': 'developer-tooling',
    'meta-knowledge': 'methodology',
    'roadmap': 'education',
    'autonomy': 'ai-agents',
    'ai-education': 'education',
    'compliance': 'security',
    'consulting': 'company',
    'opinion-leader': 'person',
    'property-based-testing': 'developer-tooling',
    'software-correctness': 'developer-tooling',
    'capabilities': 'ai-agents',
    'local-models': 'local-llm',
    'chip-design': 'hardware',
    'vc': 'company',
    'local-ai': 'local-llm',
    'books': 'writing',
    'model-spec': 'model',
    'finance-ai': 'fintech',
    'robotaxi': 'robotics',
    'amazon': 'aws',
    'cmu': 'education',
    'agent-observability': 'infrastructure',
    'mathematics': 'education',
    'standard': 'methodology',
    'w3c': 'developer-tooling',
    'reranking': 'search',
    'github': 'developer-tooling',
    'essayist': 'person',
    'startups': 'company',
    'venture-capital': 'company',
    'mlx': 'hardware',
    'jailbreak': 'agent-safety',
    'adversarial-ml': 'agent-safety',
    'symphony': 'harness-engineering',
    'clinical-ai': 'ai-adoption',
    'operations': 'infrastructure',
    'feed-readers': 'developer-tooling',
    'engineering': 'methodology',
    'simulation': 'robotics',
    'defense': 'ai-adoption',
    'ideas': 'methodology',
    'hashicorp': 'company',
    'visualization': 'developer-tooling',

    # 2026-05-11 phase3: remaining multi-use non-SCHEMA tags (from pre-commit violations)
    'async-processing': 'infrastructure',
    'steering': 'interpretability',
    'cost': 'economics',
    'context': 'context-management',
    'ai-bubble': 'economics',
    'pricing': 'economics',
    'gpu-memory': 'hardware',
    'military': 'ai-adoption',
    'pentagon': 'ai-adoption',
    'visual-reasoning': 'reasoning',
    'function-calling': 'tool',
    'file-system-memory': 'memory-systems',
    'firefox': 'company',
    'postgresql': 'database',
    'multi-token-prediction': 'inference',
    'memory-optimization': 'optimization',
    'pydantic-ai': 'developer-tooling',
    'code-mode': 'coding-agents',
    'runtime': 'infrastructure',
    'entropy': 'methodology',
    'benchmark-contamination': 'benchmark',
    'multilingual': 'model',
    'api-first': 'developer-tooling',
    'sparse-attention': 'model',
    'lmsys': 'lab',
    'epistemology': 'philosophy',
    'vercel': 'company',
    'CRDT': 'developer-tooling',
    'edge': 'infrastructure',
    'packaging': 'developer-tooling',
    'ai-ethics': 'ethics',
    'llm-int8': 'quantization',
    'fp8': 'quantization',
    'mozilla': 'company',
    'tooling': 'tool',
    'analysis': 'methodology',
    'hallucination': 'evaluation',
    'pretraining': 'training',
    'data-quality': 'training',
    'continual-learning': 'training',
    'voice-agents': 'ai-agents',
    'data-visualization': 'developer-tooling',
    'ai-engineer': 'person',
    'ai-policy': 'policy',
    'agent-monitoring': 'infrastructure',
    'dolt': 'database',
    'code-search': 'search',
    'colbert': 'search',
    'tech-policy': 'policy',
    'ai-platform': 'platform',
    'ai-models': 'model',
    'ml-systems': 'infrastructure',
    'open-source-models': 'open-source',
    'digital-humanities': 'education',
    'relevance': 'search',
    'marketplace': 'company',
    'open-weight-models': 'open-source',
    'rft': 'training',
    'local-first': 'developer-tooling',
    'enterprise-search': 'search',
    'keen-technologies': 'company',
    'service-as-software': 'ai-adoption',
    'speech-tokenizer': 'multimodal',
    'thinking-machines-lab': 'lab',
    'sre': 'infrastructure',
    'vibe-coding': 'coding-agents',
    'language': 'nlp',
    'hiring': 'company',
    'data-labeling': 'training',
    'notion': 'company',
    'front-page': 'methodology',
    'synthesis': 'methodology',
    'sql': 'database',
    'api-security': 'security',
    'ai-business-model': 'economics',
    'sharding': 'infrastructure',
    'embedding': 'model',
    'copyright': 'policy',
    'enshittification': 'methodology',
    'pipeline': 'devops',
    'swe-bench': 'benchmark',
    'logic': 'reasoning',
    'symbolic-ai': 'neurosymbolic',
    'history': 'timeline',
    'agent-sandboxing': 'sandbox',
    'datasette': 'tool',
    'pattern': 'design-patterns',
    'cognitive-science': 'psychology',
    'psychology': 'psychology',
    'academic': 'research',
    'case-study': 'methodology',
    'instruction-tuning': 'fine-tuning',
    'memory-efficiency': 'optimization',
    'knowledge-management': 'information-retrieval',
    'understanding-code': 'code-intelligence',
    'vector-database': 'vector-search',
    'computer-history': 'timeline',

    # 2026-07-27 weekly tag audit: non-SCHEMA tag mappings
    'incident': 'ai-safety',
    'ai-criticism': 'ai-critic',
    'digital-sovereignty': 'sovereign-ai',
    'longtermism': 'existential-risk',
    'wiki-maintenance': 'wiki',
    'graph-analysis': 'wiki',

    # 2026-08-10 weekly audit: multi-use non-SCHEMA tags (2x+)
    'wealth-distribution': 'economics',
    'roi': 'business-model',
    'ai-cost': 'cost',
    'token-billing': 'token-economics',

    # 2026-08-17 weekly audit: multi-use non-SCHEMA tags (2x+)
    'wealth-concentration': 'economics',
    'data-exfiltration': 'security',
}

def extract_tags_from_frontmatter(front):
    """Extract tag strings from frontmatter text."""
    tags = []
    # Block format: tags:\n  - tag1\n  - tag2 (double-space indent)
    # Also handle: tags:\n - tag1\n - tag2 (single-space indent)
    block_match = re.search(r'^tags:\n((?:[ \t]*- .*\n?)+)', front, re.MULTILINE)
    if block_match:
        for line in block_match.group(1).split('\n'):
            line = line.strip()
            if line.startswith('- '):
                tag = line[2:].strip().strip('"\'')
                if tag:
                    tags.append(tag)
        return tags
    # Inline format: tags: [tag1, tag2]
    inline_match = re.search(r'^tags:\s*\[(.+)\]', front, re.MULTILINE)
    if inline_match:
        for t in inline_match.group(1).split(','):
            tag = t.strip().strip('"\'').strip()
            if tag:
                tags.append(tag)
        return tags
    # Simple: tags: tagname
    simple_match = re.search(r'^tags:\s*(\S+)', front, re.MULTILINE)
    if simple_match:
        tags.append(simple_match.group(1).strip().strip('"\''))
    return tags

def normalize_page(content):
    """Normalize tags in frontmatter. Returns modified content or None."""
    m = re.match(r'^(---\n)(.*?)(\n---)', content, re.DOTALL)
    if not m:
        return None
    opener, front, closer = m.group(1), m.group(2), m.group(3)
    body = content[m.end():]  # CRITICAL: preserve everything after frontmatter!
    if not re.search(r'^tags:', front, re.MULTILINE):
        return None
    tags = extract_tags_from_frontmatter(front)
    if not tags:
        return None
    changed = False
    normalized = []
    for tag in tags:
        new_tag = TAG_NORMALIZATION.get(tag, tag)
        if new_tag != tag:
            changed = True
        if new_tag:
            normalized.append(new_tag)
    seen = set()
    deduped = []
    for tag in normalized:
        key = tag.lower()
        if key not in seen:
            seen.add(key)
            deduped.append(tag)
        elif tag != key:
            changed = True
    if not changed:
        return None
    new_tags_block = 'tags:\n'
    for tag in deduped:
        new_tags_block += f'  - {tag}\n'
    new_front = re.sub(
        r'^tags:.*(?:\n|$)(?:[ \t]+- .*\n?)*',
        new_tags_block,
        front,
        count=1,
        flags=re.MULTILINE
    )
    # Guard against phantom modifications: only return if content actually changed
    new_content = opener + new_front + closer + body
    if new_content == content:
        return None
    # Return FULL content: frontmatter + body
    return new_content

def main():
    dry_run = '--dry-run' in sys.argv
    modified = 0
    scanned = 0
    for root_dir in ['entities', 'concepts', 'comparisons', 'events', 'queries']:
        for root, dirs, files in os.walk(os.path.join(wiki, root_dir)):
            for f in files:
                if not f.endswith('.md'):
                    continue
                path = os.path.join(root, f)
                scanned += 1
                with open(path) as fh:
                    content = fh.read()
                new_content = normalize_page(content)
                if new_content:
                    if not dry_run:
                        with open(path, 'w') as fh:
                            fh.write(new_content)
                    rel = os.path.relpath(path, wiki)
                    status = "[DRY RUN]" if dry_run else "[MODIFIED]"
                    print(f"  {status} {rel}")
                    modified += 1
    print(f"\nScanned: {scanned} pages")
    print(f"{'Would modify' if dry_run else 'Modified'}: {modified} pages")

if __name__ == '__main__':
    main()
